/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*
 * package com.test.controller;
 * 
 * import org.springframework.web.bind.annotation.GetMapping; import
 * org.springframework.web.bind.annotation.RestController;
 * 
 * @RestController public class SimpleSpringMVCController {
 * 
 * @GetMapping("/") public String showHomePage() {
 * 
 * return "Test"; } }
 */